### ISSUE TITLE
Question - Is it possible to move the info tooltip to the right side of the screen?

### ISSUE THREAD

**Issue by sanscriptum** [aridacity/imageData#6]
I messed around with css a bit, and it wasn't obvious enough I'm afraid.

I open images in separate tabs, and I have reverse image search buttons in the left corner, so I'd like to have the info on the right side. Could that be arranged?

**Comment by cubeleco** [comment]
You can use the right css property to put the info on the right side. So to place it 3 pixels away from the right side you could add this to your custom css: `left: auto; right: 3px;`

**Comment by sanscriptum** [comment]
Excellent, that works! Thank you. Needed a browser cache clear, but it gets the job done.
